name: Build and Push Docker image to GitHub Packages on Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/limedrive/ygg-rss-proxy:latest
          # Add additional tags if needed, such as the release version
          # tags: ghcr.io/${{ github.repository_owner }}/ygg-rss-proxy:${{ github.event.release.tag_name }}
